[options]
Architecture = auto
CheckSpace
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5
NoUpgrade = etc/pacman.conf etc/locale.conf etc/vconsole.conf
NoUpgrade = etc/locale.gen etc/motd

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
