[options]
CacheDir = /var/cache/pacman/pkg/ 
HookDir = /home/heini/my_repos/archiso-workbench/builds/run-ovd2RTfj/work/x86_64/airootfs/etc/pacman.d/hooks/
GPGDir = /etc/pacman.d/gnupg/
NoUpgrade = etc/pacman.conf
NoUpgrade = etc/locale.conf
NoUpgrade = etc/vconsole.conf
NoUpgrade = etc/locale.gen
NoUpgrade = etc/motd
Architecture = x86_64
CheckSpace
ParallelDownloads = 5
CleanMethod = KeepInstalled
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
Usage = All
Server = https://mirror.bouwhuis.network/archlinux/core/os/x86_64
Server = https://mirrors.janbruckner.de/archlinux/core/os/x86_64
Server = https://archmirror.hogwarts.fr/core/os/x86_64
Server = https://mirror.netcologne.de/archlinux/core/os/x86_64
Server = https://mirror.hugo-betrugo.de/archlinux/core/os/x86_64
Server = https://arch.ljkx.org/core/os/x86_64
Server = https://mirror.ipb.de/archlinux/core/os/x86_64
Server = https://mirror.pseudoform.org/core/os/x86_64
Server = https://berlin.mirror.pkgbuild.com/core/os/x86_64
Server = https://mirrors.n-ix.net/archlinux/core/os/x86_64
Server = https://ftp.lysator.liu.se/pub/archlinux/core/os/x86_64
Server = https://ftp.fau.de/archlinux/core/os/x86_64
[extra]
Usage = All
Server = https://mirror.bouwhuis.network/archlinux/extra/os/x86_64
Server = https://mirrors.janbruckner.de/archlinux/extra/os/x86_64
Server = https://archmirror.hogwarts.fr/extra/os/x86_64
Server = https://mirror.netcologne.de/archlinux/extra/os/x86_64
Server = https://mirror.hugo-betrugo.de/archlinux/extra/os/x86_64
Server = https://arch.ljkx.org/extra/os/x86_64
Server = https://mirror.ipb.de/archlinux/extra/os/x86_64
Server = https://mirror.pseudoform.org/extra/os/x86_64
Server = https://berlin.mirror.pkgbuild.com/extra/os/x86_64
Server = https://mirrors.n-ix.net/archlinux/extra/os/x86_64
Server = https://ftp.lysator.liu.se/pub/archlinux/extra/os/x86_64
Server = https://ftp.fau.de/archlinux/extra/os/x86_64
